import {
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiTypescript,
  SiRedux,
  SiFramer,
  SiNodedotjs,
  SiNestjs,
  SiPrisma,
  SiPostgresql,
  SiMongodb,
  SiGraphql,
  SiDocker,
  SiGit,
  SiGithub,
  SiVercel,
  SiJest,
  SiCypress,
  SiHtml5,
  SiFirebase,
  SiBootstrap,
  SiMaterialdesign,
  SiCss3,
  SiGoogleanalytics,
  SiJavascript,
  SiGulp,
  SiSupabase,
} from "react-icons/si";

export const skills = {
  frontend: [
    { name: "React", icon: SiReact, color: "#61DAFB" },
    { name: "React Native", icon: SiReact, color: "#61DAFB" },
    { name: "HTML", icon: SiHtml5, color: "#61DAFB" },
    { name: "Next.js", icon: SiNextdotjs, color: "#ffffff" },
    { name: "CSS", icon: SiCss3, color: "#61DAFB" },
    { name: "Google Analytics", icon: SiGoogleanalytics, color: "#E10098" },
    { name: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
    { name: "TailwindCSS", icon: SiTailwindcss, color: "#38BDF8" },
    { name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
    { name: "Redux", icon: SiRedux, color: "#764ABC" },
    { name: "Framer Motion", icon: SiFramer, color: "#E10098" },
    { name: "Bootstrap", icon: SiBootstrap, color: "#7952B3" },
    { name: "Material UI", icon: SiMaterialdesign, color: "#0081CB" },
  ],
  backend: [
    { name: "Node.js", icon: SiNodedotjs, color: "#68A063" },
    { name: "NestJS", icon: SiNestjs, color: "#E0234E" },
    { name: "Prisma", icon: SiPrisma, color: "#2D3748" },
    { name: "PostgreSQL", icon: SiPostgresql, color: "#4169E1" },
    { name: "MongoDB", icon: SiMongodb, color: "#47A248" },
    { name: "GraphQL", icon: SiGraphql, color: "#E10098" },
    { name: "Firebase", icon: SiFirebase, color: "#FFCA28" },
    { name: "Supabase", icon: SiSupabase, color: "#3ECF8E" },
  ],
  tools: [
    { name: "Docker", icon: SiDocker, color: "#2496ED" },
    { name: "Git", icon: SiGit, color: "#F05032" },
    { name: "GitHub", icon: SiGithub, color: "#ffffff" },
    { name: "Vercel", icon: SiVercel, color: "#ffffff" },
    { name: "Jest", icon: SiJest, color: "#99425B" },
    { name: "Cypress", icon: SiCypress, color: "#69D3A7" },
    { name: "Gulp", icon: SiGulp, color: "#CF4647" },
  ],
};

